repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-added-large-files
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  -   id: black
      files: moonpy
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.4.1
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
    - id: nbqa-isort
      additional_dependencies: [isort==5.6.4]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.7.4]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.4
  hooks:
    - id: pyupgrade
      args: [--py36-plus]
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
